import React from "react";
import ProductCard from "../ProductCard/ProductCard";
import "./ProductList.scss";

const ProductList = () => {
  const data = [
    {
      id: 1,
      img1: "mainSliderImg1.jpg",
      img2: "mainSliderImg4.png",
      name: "KEYBOARD",
      price: "R 199.99",
    },
    {
      id: 2,
      img1: "mainSliderImg2.jpg",
      img2: "mainSliderImg3.jpg",
      name: "MOUSE",
      price: "FROM R 399.00",
    },
    {
      id: 3,
      img1: "mainSliderImg3.jpg",
      img2: "mainSliderImg1.jpg",
      name: "CPU",
      price: "FROM R 799.99",
    },
    {
      id: 4,
      img1: "mainSliderImg4.png",
      img2: "mainSliderImg2.jpg",
      name: "HEADPHONES",
      price: "R 99.99",
    },
    {
      id: 5,
      img1: "mainSliderImg1.jpg",
      img2: "mainSliderImg4.png",
      name: "KEYBOARD",
      price: "R 199.99",
    },
    {
      id: 6,
      img1: "mainSliderImg2.jpg",
      img2: "mainSliderImg3.jpg",
      name: "MOUSE",
      price: "FROM R 399.00",
    },
    {
      id: 7,
      img1: "mainSliderImg3.jpg",
      img2: "mainSliderImg1.jpg",
      name: "CPU",
      price: "FROM R 799.99",
    },
    {
      id: 8,
      img1: "mainSliderImg4.png",
      img2: "mainSliderImg2.jpg",
      name: "HEADPHONES",
      price: "R 99.99",
    },
    {
      id: 9,
      img1: "mainSliderImg1.jpg",
      img2: "mainSliderImg4.png",
      name: "KEYBOARD",
      price: "R 199.99",
    },
    {
      id: 10,
      img1: "mainSliderImg2.jpg",
      img2: "mainSliderImg3.jpg",
      name: "MOUSE",
      price: "FROM R 399.00",
    },
    {
      id: 11,
      img1: "mainSliderImg3.jpg",
      img2: "mainSliderImg1.jpg",
      name: "CPU",
      price: "FROM R 799.99",
    },
    {
      id: 12,
      img1: "mainSliderImg4.png",
      img2: "mainSliderImg2.jpg",
      name: "HEADPHONES",
      price: "R 99.99",
    },
    {
      id: 13,
      img1: "mainSliderImg1.jpg",
      img2: "mainSliderImg4.png",
      name: "KEYBOARD",
      price: "R 199.99",
    },
    {
      id: 14,
      img1: "mainSliderImg2.jpg",
      img2: "mainSliderImg3.jpg",
      name: "MOUSE",
      price: "FROM R 399.00",
    },
    {
      id: 15,
      img1: "mainSliderImg3.jpg",
      img2: "mainSliderImg1.jpg",
      name: "CPU",
      price: "FROM R 799.99",
    },
    {
      id: 16,
      img1: "mainSliderImg4.png",
      img2: "mainSliderImg2.jpg",
      name: "HEADPHONES",
      price: "R 99.99",
    },
    {
      id: 17,
      img1: "mainSliderImg1.jpg",
      img2: "mainSliderImg4.png",
      name: "KEYBOARD",
      price: "R 199.99",
    },
    {
      id: 18,
      img1: "mainSliderImg2.jpg",
      img2: "mainSliderImg3.jpg",
      name: "MOUSE",
      price: "FROM R 399.00",
    },
    {
      id: 19,
      img1: "mainSliderImg3.jpg",
      img2: "mainSliderImg1.jpg",
      name: "CPU",
      price: "FROM R 799.99",
    },
    {
      id: 20,
      img1: "mainSliderImg4.png",
      img2: "mainSliderImg2.jpg",
      name: "HEADPHONES",
      price: "R 99.99",
    },
    {
      id: 21,
      img1: "mainSliderImg1.jpg",
      img2: "mainSliderImg4.png",
      name: "KEYBOARD",
      price: "R 199.99",
    },
    {
      id: 22,
      img1: "mainSliderImg2.jpg",
      img2: "mainSliderImg3.jpg",
      name: "MOUSE",
      price: "FROM R 399.00",
    },
    {
      id: 23,
      img1: "mainSliderImg3.jpg",
      img2: "mainSliderImg1.jpg",
      name: "CPU",
      price: "FROM R 799.99",
    },
    {
      id: 24,
      img1: "mainSliderImg4.png",
      img2: "mainSliderImg2.jpg",
      name: "HEADPHONES",
      price: "R 99.99",
    },
    {
      id: 25,
      img1: "mainSliderImg1.jpg",
      img2: "mainSliderImg4.png",
      name: "KEYBOARD",
      price: "R 199.99",
    },
    {
      id: 26,
      img1: "mainSliderImg2.jpg",
      img2: "mainSliderImg3.jpg",
      name: "MOUSE",
      price: "FROM R 399.00",
    },
    {
      id: 27,
      img1: "mainSliderImg3.jpg",
      img2: "mainSliderImg1.jpg",
      name: "CPU",
      price: "FROM R 799.99",
    },
    {
      id: 28,
      img1: "mainSliderImg4.png",
      img2: "mainSliderImg2.jpg",
      name: "HEADPHONES",
      price: "R 99.99",
    },
    {
      id: 29,
      img1: "mainSliderImg1.jpg",
      img2: "mainSliderImg4.png",
      name: "KEYBOARD",
      price: "R 199.99",
    },
    {
      id: 30,
      img1: "mainSliderImg2.jpg",
      img2: "mainSliderImg3.jpg",
      name: "MOUSE",
      price: "FROM R 399.00",
    },
    {
      id: 31,
      img1: "mainSliderImg3.jpg",
      img2: "mainSliderImg1.jpg",
      name: "CPU",
      price: "FROM R 799.99",
    },
    {
      id: 32,
      img1: "mainSliderImg4.png",
      img2: "mainSliderImg2.jpg",
      name: "HEADPHONES",
      price: "R 99.99",
    },
    {
      id: 33,
      img1: "mainSliderImg1.jpg",
      img2: "mainSliderImg4.png",
      name: "KEYBOARD",
      price: "R 199.99",
    },
    {
      id: 34,
      img1: "mainSliderImg2.jpg",
      img2: "mainSliderImg3.jpg",
      name: "MOUSE",
      price: "FROM R 399.00",
    },
    {
      id: 35,
      img1: "mainSliderImg3.jpg",
      img2: "mainSliderImg1.jpg",
      name: "CPU",
      price: "FROM R 799.99",
    },
    {
      id: 36,
      img1: "mainSliderImg4.png",
      img2: "mainSliderImg2.jpg",
      name: "HEADPHONES",
      price: "R 99.99",
    },
    {
      id: 37,
      img1: "mainSliderImg1.jpg",
      img2: "mainSliderImg4.png",
      name: "KEYBOARD",
      price: "R 199.99",
    },
    {
      id: 38,
      img1: "mainSliderImg2.jpg",
      img2: "mainSliderImg3.jpg",
      name: "MOUSE",
      price: "FROM R 399.00",
    },
    {
      id: 39,
      img1: "mainSliderImg3.jpg",
      img2: "mainSliderImg1.jpg",
      name: "CPU",
      price: "FROM R 799.99",
    },
  ];

  return (
    <div className="productList">
      {data.map((item) => (
        <ProductCard item={item} key={item.id} />
      ))}
    </div>
  );
};

export default ProductList;
