import React from "react";
import Footer from "../../components/Footer/Footer";
import Header from "../../components/Header/Header";
import Navbar from "../../components/Navbar/Navbar";
import "./PrivacyPolicy.scss";

const PrivacyPolicy = () => {
  return (
    <>
      <Navbar />
      <Header title="PRIVACY POLICY" />
      <div className="privacyPolicy">
        <div className="section">
          <p className="heading">INTERPRETATION</p>
          <p className="subHeading">
            The words of which the initial letter is capitalized have meanings
            defined under the following conditions.
          </p>
          <p className="subHeading">
            The following definitions shall have the same meaning regardless of
            whether they appear in singular or in plural.
          </p>
        </div>
        <div className="section">
          <p className="heading">DEFINITIONS</p>
          <p className="subHeading">For the purposes of this Privacy Policy:</p>
          <ul className="points">
            <li>
              <strong>You</strong> mean the individual accessing or using the
              Service, or the company, or other legal entity on behalf of which
              such individual is accessing or using the Service, as applicable.
            </li>
            <li>
              <strong>Company</strong>&nbsp;(referred to as either "the
              Company", "We", "Us" or "Our" in this Agreement) refers to JD
              Elite, G-2, Matharu Arcade, 32 Subhash Road, Vile Parle East,
              Mumbai : 400 057.
            </li>
            <li>
              <strong>Affiliate</strong> means an entity that controls, is
              controlled by, or is under common control with a party, where
              "control" means ownership of 50% or more of the shares, equity
              interest or other securities entitled to vote for election of
              directors or other managing authority.
            </li>
            <li>
              <strong>Account</strong>&nbsp;means a unique account created for
              You to access our Service or parts of our Service.
            </li>
            <li>
              <strong>Website</strong>&nbsp;refers to EliteHubs, accessible from
              www.elitehubs.com
            </li>
            <li>
              <strong>Service</strong>&nbsp;refers to the Website.
            </li>
            <li>
              <strong>Country</strong>&nbsp;refers to: Maharashtra, India
            </li>
            <li>
              <strong>Service Provider</strong>&nbsp;means any natural or legal
              person who processes the data on behalf of the Company. It refers
              to third-party companies or individuals employed by the Company to
              facilitate the Service, to provide the Service on behalf of the
              Company, to perform services related to the Service or to assist
              the Company in analyzing how the Service is used.
            </li>
            <li>
              <strong>Third-party Social Media Service</strong>&nbsp;refers to
              any website or any social network website through which a User can
              log in or create an account to use the Service.
            </li>
            <li>
              <strong>Personal Data</strong>&nbsp;is any information that
              relates to an identified or identifiable individual.
            </li>
            <li>
              <strong>Cookies</strong>&nbsp;are small files that are placed on
              Your computer, mobile device or any other device by a website,
              containing the details of Your browsing history on that website
              among its many uses.
            </li>
            <li>
              <strong>Device</strong>&nbsp;means any device that can access the
              Service such as a computer, a cellphone or a digital tablet.
            </li>
            <li>
              <strong>Usage Data</strong>&nbsp;refers to data collected
              automatically, either generated by the use of the Service or from
              the Service infrastructure itself (for example, the duration of a
              page visit).
            </li>
          </ul>
        </div>
      </div>
      <Footer />
    </>
  );
};

export default PrivacyPolicy;
