import React from "react";
import Footer from "../../components/Footer/Footer";
import Header from "../../components/Header/Header";
import Navbar from "../../components/Navbar/Navbar";
import "./PrivacyPolicy.scss";

const PrivacyPolicy = () => {
  return (
    <>
      <Navbar />
      <Header title="PRIVACY POLICY" />
      <div className="privacyPolicy">
        <div className="section">
          <p className="heading">INTERPRETATION</p>
          <p className="subHeading">
            The words of which the initial letter is capitalized have meanings
            defined under the following conditions.
          </p>
          <p className="subHeading">
            The following definitions shall have the same meaning regardless of
            whether they appear in singular or in plural.
          </p>
        </div>
        <div className="section">
          <p className="heading">DEFINITIONS</p>
          <p className="subHeading">For the purposes of this Privacy Policy:</p>
          <ul className="points">
            <li>
              <strong>You</strong> mean the individual accessing or using the
              Service, or the company, or other legal entity on behalf of which
              such individual is accessing or using the Service, as applicable.
            </li>
            <li>
              <strong>Company</strong>&nbsp;(referred to as either "the
              Company", "We", "Us" or "Our" in this Agreement) refers to JD
              Elite, G-2, Matharu Arcade, 32 Subhash Road, Vile Parle East,
              Mumbai : 400 057.
            </li>
            <li>
              <strong>Affiliate</strong> means an entity that controls, is
              controlled by, or is under common control with a party, where
              "control" means ownership of 50% or more of the shares, equity
              interest or other securities entitled to vote for election of
              directors or other managing authority.
            </li>
            <li>
              <strong>Account</strong>&nbsp;means a unique account created for
              You to access our Service or parts of our Service.
            </li>
            <li>
              <strong>Website</strong>&nbsp;refers to EliteHubs, accessible from
              www.elitehubs.com
            </li>
            <li>
              <strong>Service</strong>&nbsp;refers to the Website.
            </li>
            <li>
              <strong>Country</strong>&nbsp;refers to: Maharashtra, India
            </li>
            <li>
              <strong>Service Provider</strong>&nbsp;means any natural or legal
              person who processes the data on behalf of the Company. It refers
              to third-party companies or individuals employed by the Company to
              facilitate the Service, to provide the Service on behalf of the
              Company, to perform services related to the Service or to assist
              the Company in analyzing how the Service is used.
            </li>
            <li>
              <strong>Third-party Social Media Service</strong>&nbsp;refers to
              any website or any social network website through which a User can
              log in or create an account to use the Service.
            </li>
            <li>
              <strong>Personal Data</strong>&nbsp;is any information that
              relates to an identified or identifiable individual.
            </li>
            <li>
              <strong>Cookies</strong>&nbsp;are small files that are placed on
              Your computer, mobile device or any other device by a website,
              containing the details of Your browsing history on that website
              among its many uses.
            </li>
            <li>
              <strong>Device</strong>&nbsp;means any device that can access the
              Service such as a computer, a cellphone or a digital tablet.
            </li>
            <li>
              <strong>Usage Data</strong>&nbsp;refers to data collected
              automatically, either generated by the use of the Service or from
              the Service infrastructure itself (for example, the duration of a
              page visit).
            </li>
          </ul>
        </div>
        <div className="section">
          <p className="heading">PERSONAL DATA</p>
          <p className="subHeading">
            While using Our Service, We may ask You to provide Us with certain
            personally identifiable information that can be used to contact or
            identify You. Personally identifiable information may include, but
            is not limited to:
          </p>
          <ul className="points">
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Phone number</li>
            <li>Address, State, Province, ZIP/Postal code, City</li>
            <li>
              Bank account information in order to pay for products and/or
              services within the Service
            </li>
            <li>Usage Data</li>
          </ul>
          <p className="subHeading">
            When You pay for a product and/or a service via bank transfer, We
            may ask You to provide information to facilitate this transaction
            and to verify Your identity. Such information may include, without
            limitation:
          </p>
          <ul className="points">
            <li>Date of birth</li>
            <li>Passport or National ID card</li>
            <li>Bank card statement</li>
            <li>Other information linking You to an address</li>
          </ul>
        </div>
        <div className="section">
          <p className="heading">USAGE DATA</p>
          <p className="subHeading">
            Usage Data is collected automatically when using the Service.
          </p>
          <p className="subHeading">
            Usage Data may include information such as Your Device's Internet
            Protocol address (e.g. IP address), browser type, browser version,
            the pages of our Service that You visit, the time and date of Your
            visit, the time spent on those pages, unique device identifiers and
            other diagnostic data.
          </p>
          <p className="subHeading">
            When You access the Service by or through a mobile device, We may
            collect certain information automatically, including, but not
            limited to, the type of mobile device You use, Your mobile device
            unique ID, the IP address of Your mobile device, Your mobile
            operating system, the type of mobile Internet browser You use,
            unique device identifiers and other diagnostic data.
          </p>
          <p className="subHeading">
            We may also collect information that Your browser sends whenever You
            visit our Service or when You access the Service by or through a
            mobile device.
          </p>
        </div>
        <div className="section">
          <p className="heading">
            INFORMATION FROM THIRD PARTY SOCIAL MEDIA SERVICES
          </p>
          <p className="subHeading">
            The Company allows You to create an account and log in to use the
            Service through the following Third-party Social Media Services:
          </p>
          <p className="subHeading">
            If You decide to register through or otherwise grant us access to a
            Third-Party Social Media Service, We may collect Personal data that
            is already associated with Your Third-Party Social Media Service's
            account, such as Your name, Your email address, Your activities or
            Your contact list associated with that account.
          </p>
          <ul className="points">
            <li>Google</li>
            <li>Facebook</li>
            <li>Twitter</li>
          </ul>
          <p className="subHeading">
            If You decide to register through or otherwise grant us access to a
            Third-Party Social Media Service, We may collect Personal data that
            is already associated with Your Third-Party Social Media Service's
            account, such as Your name, Your email address, Your activities or
            Your contact list associated with that account.
          </p>
        </div>
        <div className="section">
          <p className="heading">TRACKING TECHNOLOGIES & COOKIES</p>
          <p className="subHeading">
            We use Cookies and similar tracking technologies to track the
            activity on Our Service and store certain information. Tracking
            technologies used are beacons, tags, and scripts to collect and
            track information and to improve and analyze Our Service.
          </p>
          <p className="subHeading">
            Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies
            remain on your personal computer or mobile device when You go
            offline, while Session Cookies are deleted as soon as You close your
            web browser. Learn more about cookies in the "What Are Cookies"
            article.
          </p>
          <p className="subHeading">
            We use both session and persistent cookies for the purposes set out
            below:
          </p>
          <ul className="points">
            <li>
              <strong>Necessary / Essential Cookies</strong> Type: Session
              Cookies Administered by: Us Purpose: These cookies are essential
              to provide You with services available through the Website and to
              enable You to use some of its features. They help to authenticate
              users and prevent fraudulent use of user accounts. Without these
              Cookies, the services that You have asked for cannot be provided,
              and We only use these Cookies to provide You with those services.
            </li>
            <li>
              <strong>Cookies Policy / Notice Acceptance Cookies</strong> Type:
              Persistent Cookies Administered by: Us Purpose: These Cookies
              identify if users have accepted the use of cookies on the Website.
            </li>
            <li>
              <strong>Functionality Cookies</strong> Type: Persistent Cookies
              Administered by: Us Purpose: These Cookies allow us to remember
              choices You make when You use the Website, such as remembering
              your login details or language preference. The purpose of these
              Cookies is to provide You with a more personal experience and to
              avoid You having to re-enter your preferences every time You use
              the Website.
            </li>
            <li>
              <strong>Tracking and Performance Cookies</strong> Type: Persistent
              Cookies Administered by: Third-Parties Purpose: These Cookies are
              used to track information about traffic to the Website and how
              users use the Website. The information gathered via these Cookies
              may directly or indirectly identify you as an individual visitor.
              This is because the information collected is typically linked to a
              pseudonymous identifier associated with the device you use to
              access the Website. We may also use these Cookies to test new
              advertisements, pages, features or new functionality of the
              Website to see how our users react to them.
            </li>
            <li>
              <strong>Targeting and Advertising Cookies</strong> Type:
              Persistent Cookies Administered by: Third-Parties Purpose: These
              Cookies track your browsing habits to enable Us to show
              advertising which is more likely to be of interest to You. These
              Cookies use information about your browsing history to group You
              with other users who have similar interests. Based on that
              information, and with Our permission, third party advertisers can
              place Cookies to enable them to show adverts which We think will
              be relevant to your interests while You are on third party
              websites.
            </li>
          </ul>
          <p className="subHeading">
            For more information about the cookies we use and your choices
            regarding cookies, please visit our Cookies Policy.
          </p>
        </div>
        <div className="section">
          <p className="heading">USE OF YOUR PERSONAL DATA</p>
          <p className="subHeading">
            The Company may use Personal Data for the following purposes:
          </p>
          <ul className="points">
            <li>
              <strong>To provide and maintain our Service</strong>, including to
              monitor the usage of our Service.
            </li>
            <li>
              <strong>To manage Your Account:</strong>&nbsp;to manage Your
              registration as a user of the Service. The Personal Data You
              provide can give You access to different functionalities of the
              Service that are available to You as a registered user.
            </li>
            <li>
              <strong>For the performance of a contract:</strong> the
              development, compliance, and undertaking of the purchase contract
              for the products, items or services You have purchased or of any
              other contract with Us through the Service.
            </li>
            <li>
              <strong>To contact You:</strong>&nbsp;To contact You by email,
              telephone calls, SMS, or other equivalent forms of electronic
              communication, such as a mobile application's push notifications
              regarding updates or informative communications related to the
              functionalities, products or contracted services, including the
              security updates, when necessary or reasonable for their
              implementation.
            </li>
            <li>
              <strong>To provide You</strong> with news, special offers, and
              general information about other goods, services, and events which
              we offer that are similar to those that you have already purchased
              or enquired about unless You have opted not to receive such
              information.
            </li>
            <li>
              <strong>To manage Your requests:</strong>&nbsp;To attend and
              manage Your requests to Us.
            </li>
          </ul>
          <p className="subHeading">
            We may share your personal information in the following situations:
          </p>
          <ul className="points">
            <li>
              <strong>With Service Providers:</strong>&nbsp;We may share Your
              personal information with Service Providers to monitor and analyze
              the use of our Service, to show advertisements to You to help
              support and maintain Our Service, to advertise on third party
              websites to You after You visited our Service, for payment
              processing, to contact You.
            </li>
            <li>
              <strong>For Business transfers:</strong> We may share or transfer
              Your personal information in connection with, or during
              negotiations of, any merger, sale of company assets, financing, or
              acquisition of all or a portion of our business to another
              company.
            </li>
            <li>
              <strong>With Affiliates:</strong>&nbsp;We may share Your
              information with Our affiliates, in which case we will require
              those affiliates to honor this Privacy Policy. Affiliates include
              Our parent company and any other subsidiaries, joint venture
              partners or other companies that We control or that are under
              common control with Us.
            </li>
            <li>
              <strong>With Business Partners:</strong>&nbsp;We may share Your
              information with Our business partners to offer You certain
              products, services or promotions.
            </li>
            <li>
              <strong>With other users:</strong>&nbsp;when You share personal
              information or otherwise interact in the public areas with other
              users, such information may be viewed by all users and may be
              publicly distributed outside. If You interact with other users or
              register through a Third-Party Social Media Service, Your contacts
              on the Third-Party Social Media Service may see Your name,
              profile, pictures and description of Your activity. Similarly,
              other users will be able to view descriptions of Your activity,
              communicate with You and view Your profile.
            </li>
          </ul>
        </div>
        <div className="section">
          <p className="heading">RETENTION OF YOUR PERSONAL DATA</p>
          <p className="subHeading">
            The Company will retain Your Personal Data only for as long as is
            necessary for the purposes set out in this Privacy Policy. We will
            retain and use Your Personal Data to the extent necessary to comply
            with our legal obligations (for example, if we are required to
            retain your data to comply with applicable laws), resolve disputes,
            and enforce our legal agreements and policies.
          </p>
          <p className="subHeading">
            The Company will also retain Usage Data for internal analysis
            purposes. Usage Data is generally retained for a shorter period of
            time, except when this data is used to strengthen the security or to
            improve the functionality of Our Service, or We are legally
            obligated to retain this data for longer time periods.
          </p>
        </div>
        <div className="section">
          <p className="heading">TRANSFER OF YOUR PERSONAL DATA</p>
          <p className="subHeading">
            Your information, including Personal Data, is processed at the
            Company's operating offices and in any other places where the
            parties involved in the processing are located. It means that this
            information may be transferred to — and maintained on — computers
            located outside of Your state, province, country or other
            governmental jurisdiction where the data protection laws may differ
            than those from Your jurisdiction.
          </p>
          <p className="subHeading">
            Your consent to this Privacy Policy followed by Your submission of
            such information represents Your agreement to that transfer.
          </p>
          <p className="subHeading">
            The Company will take all steps reasonably necessary to ensure that
            Your data is treated securely and in accordance with this Privacy
            Policy and no transfer of Your Personal Data will take place to an
            organization or a country unless there are adequate controls in
            place including the security of Your data and other personal
            information.
          </p>
        </div>
        <div className="section">
          <p className="heading">BUSINESS TRANSACTIONS</p>
          <p className="subHeading">
            If the Company is involved in a merger, acquisition or asset sale,
            Your Personal Data may be transferred. We will provide notice before
            Your Personal Data is transferred and becomes subject to a different
            Privacy Policy.
          </p>
        </div>
        <div className="section">
          <p className="heading">LAW ENFORCEMENT</p>
          <p className="subHeading">
            Under certain circumstances, the Company may be required to disclose
            Your Personal Data if required to do so by law or in response to
            valid requests by public authorities (e.g. a court or a government
            agency).
          </p>
        </div>
        <div className="section">
          <p className="heading">OTHER LEGAL REQUIREMENTS</p>
          <p className="subHeading">
            The Company may disclose Your Personal Data in the good faith belief
            that such action is necessary to:
          </p>
          <ul className="points">
            <li>Comply with a legal obligation</li>
            <li>Protect and defend the rights or property of the Company</li>
            <li>
              Prevent or investigate possible wrongdoing in connection with the
              Service
            </li>
            <li>
              Protect the personal safety of Users of the Service or the public
            </li>
            <li>Protect against legal liability</li>
          </ul>
        </div>
        <div className="section">
          <p className="heading">SECURITY OF YOUR PERSONAL DATA</p>
          <p className="subHeading">
            The security of Your Personal Data is important to Us, but remember
            that no method of transmission over the Internet, or method of
            electronic storage is 100% secure. While We strive to use
            commercially acceptable means to protect Your Personal Data, We
            cannot guarantee its absolute security.
          </p>
        </div>
        <div className="section">
          <p className="heading">ANALYTICS</p>
          <p className="subHeading">
            We may use third-party Service providers to monitor and analyze the
            use of our Service.
          </p>
          <ul className="points">
            <li>
              <li>
                <strong>Google Analytics</strong> Google Analytics is a web
                analytics service offered by Google that tracks and reports
                website traffic. Google uses the data collected to track and
                monitor the use of our Service. This data is shared with other
                Google services. Google may use the collected data to
                contextualise and personalise the ads of its own advertising
                network. You can opt-out of having made your activity on the
                Service available to Google Analytics by installing the Google
                Analytics opt-out browser add-on. The add-on prevents the Google
                Analytics JavaScript (ga.js, analytics.js and dc.js) from
                sharing information with Google Analytics about visits activity.
                For more information on the privacy practices of Google, please
                visit the Google Privacy &amp; Terms web page:&nbsp;
                <a href="https://policies.google.com/privacy?hl=en">
                  https://policies.google.com/privacy?hl=en
                </a>
              </li>
            </li>
          </ul>
        </div>
        <div className="section">
          <p className="heading">ADVERTISING</p>
          <p className="subHeading">
            We may use Service providers to show advertisements to You to help
            support and maintain Our Service.
          </p>
          <ul className="points">
            <li>
              <strong>Google AdSense &amp; DoubleClick Cookie</strong> Google,
              as a third-party vendor, uses cookies to serve ads on our Service.
              Google's use of the DoubleClick cookie enables it and its partners
              to serve ads to our users based on their visit to our Service or
              other websites on the Internet. You may opt-out of the use of the
              DoubleClick Cookie for interest-based advertising by visiting the
              Google Ads Settings web page:{" "}
              <a href="https://www.google.com/ads/preferences/">
                http://www.google.com/ads/preferences/
              </a>
            </li>
          </ul>
        </div>
        <div className="section">
          <p className="heading">EMAIL MARKETING</p>
          <p className="subHeading">
            We may use Your Personal Data to contact You with newsletters,
            marketing or promotional materials and other information that may be
            of interest to You. You may opt-out of receiving any, or all, of
            these communications from Us by following the unsubscribe link or
            instructions provided in any email We send or by contacting Us.
          </p>
          <p className="subHeading">
            We may use Email Marketing Service Providers to manage and send
            emails to You.
          </p>
          <ul className="points">
            <li>
              <strong>Mailchimp</strong> Mailchimp is an email marketing sending
              service provided by The Rocket Science Group LLC. For more
              information on the privacy practices of Mailchimp, please visit
              their Privacy policy:&nbsp;
              <a href="https://mailchimp.com/legal/privacy/">
                https://mailchimp.com/legal/privacy/
              </a>
            </li>
          </ul>
        </div>
        <div className="section">
          <p className="heading">BEHAVIORAL REMARKETING</p>
          <p className="subHeading">
            The Company uses remarketing services to advertise on third party
            websites to You after You visited our Service. We and Our
            third-party vendors use cookies to inform, optimize and serve ads
            based on Your past visits to our Service.
          </p>
          <ul className="points">
            <li>
              <strong>Google Ads (AdWords)</strong> Google Ads (AdWords)
              remarketing service is provided by Google Inc. You can opt-out of
              Google Analytics for Display Advertising and customize the Google
              Display Network ads by visiting the Google Ads Settings page:{" "}
              <a href="https://www.google.com/settings/ads">
                http://www.google.com/settings/ads
              </a>{" "}
              Google also recommends installing the Google Analytics Opt-out
              Browser Add-on -&nbsp;
              <a href="https://tools.google.com/dlpage/gaoptout">
                https://tools.google.com/dlpage/gaoptout
              </a>
              &nbsp;- for your web browser. Google Analytics Opt-out Browser
              Add-on provides visitors with the ability to prevent their data
              from being collected and used by Google Analytics. For more
              information on the privacy practices of Google, please visit the
              Google Privacy &amp; Terms web page:&nbsp;
              <a href="https://policies.google.com/privacy?hl=en">
                https://policies.google.com/privacy?hl=en
              </a>
            </li>
            <li>
              <strong>Bing Ads Remarketing</strong> Bing Ads remarketing service
              is provided by Microsoft Inc. You can opt-out of Bing Ads
              interest-based ads by following their instructions:&nbsp;
              <a href="https://advertise.bingads.microsoft.com/en-us/resources/policies/personalized-ads">
                https://advertise.bingads.microsoft.com/en-us/resources/policies/personalized-ads
              </a>{" "}
              You can learn more about the privacy practices and policies of
              Microsoft by visiting their Privacy Policy page:&nbsp;
              <a href="https://privacy.microsoft.com/en-us/PrivacyStatement">
                https://privacy.microsoft.com/en-us/PrivacyStatement
              </a>
            </li>
            <li>
              <strong>Facebook</strong> Facebook remarketing service is provided
              by Facebook Inc. You can learn more about interest-based
              advertising from Facebook by visiting this page:&nbsp;
              <a href="https://www.facebook.com/help/164968693837950">
                https://www.facebook.com/help/164968693837950
              </a>{" "}
              To opt-out from Facebook's interest-based ads, follow these
              instructions from Facebook:&nbsp;
              <a href="https://www.facebook.com/help/568137493302217">
                https://www.facebook.com/help/568137493302217
              </a>{" "}
              Facebook adheres to the Self-Regulatory Principles for Online
              Behavioural Advertising established by the Digital Advertising
              Alliance. You can also opt-out from Facebook and other
              participating companies through the Digital Advertising Alliance
              in the USA&nbsp;
              <a href="http://www.aboutads.info/choices/">
                http://www.aboutads.info/choices/
              </a>
              , the Digital Advertising Alliance of Canada in Canada&nbsp;
              <a href="http://youradchoices.ca/">http://youradchoices.ca/</a>
              &nbsp;or the European Interactive Digital Advertising Alliance in
              Europe&nbsp;
              <a href="http://www.youronlinechoices.eu/">
                http://www.youronlinechoices.eu/
              </a>
              , or opt-out using your mobile device settings. For more
              information on the privacy practices of Facebook, please visit
              Facebook's Data Policy:&nbsp;
              <a href="https://www.facebook.com/privacy/explanation">
                https://www.facebook.com/privacy/explanation
              </a>
            </li>
          </ul>
        </div>
        <div className="section">
          <p className="heading">PAYMENTS</p>
          <p className="subHeading">
            We may provide paid products and/or services within the Service. In
            that case, we may use third-party services for payment processing
            (e.g. payment processors).
          </p>
          <p className="subHeading">
            We will not store or collect Your payment card details. That
            information is provided directly to Our third-party payment
            processors whose use of Your personal information is governed by
            their Privacy Policy. These payment processors adhere to the
            standards set by PCI-DSS as managed by the PCI Security Standards
            Council, which is a joint effort of brands like Visa, Mastercard,
            American Express and Discover. PCI-DSS requirements help ensure the
            secure handling of payment information.
          </p>
          <ul className="points">
            <li>
              <strong>Google Play In-App Payments</strong> Their Privacy Policy
              can be viewed at&nbsp;
              <a href="https://www.google.com/policies/privacy/">
                https://www.google.com/policies/privacy/
              </a>
            </li>
          </ul>
          <p className="subHeading">
            When You use Our Service to pay a product and/or service via bank
            transfer, We may ask You to provide information to facilitate this
            transaction and to verify Your identity.
          </p>
        </div>
        <div className="section">
          <p className="heading">CHILDREN'S PRIVACY</p>
          <p className="subHeading">
            Our Service does not address anyone under the age of 13. We do not
            knowingly collect personally identifiable information from anyone
            under the age of 13. If You are a parent or guardian and You are
            aware that Your child has provided Us with Personal Data, please
            Contact Us. If We become aware that We have collected Personal Data
            from anyone under the age of 13 without verification of parental
            consent, We take steps to remove that information from Our servers.
          </p>
        </div>
        <div className="section">
          <p className="heading">LINKS TO OTHER WEBSITES</p>
          <p className="subHeading">
            Our Service may contain links to other websites that are not
            operated by Us. If You click on a third party link, You will be
            directed to that third party's site. We strongly advise You to
            review the Privacy Policy of every site You visit.
          </p>
          <p className="subHeading">
            We have no control over and assume no responsibility for the
            content, privacy policies or practices of any third party sites or
            services.
          </p>
        </div>
        <div className="section">
          <p className="heading">CHANGES IN PRIVACY POLICY</p>
          <p className="subHeading">
            We may update our Privacy Policy from time to time. We will notify
            You of any changes by posting the new Privacy Policy on this page.
          </p>
          <p className="subHeading">
            We will let You know via email and/or a prominent notice on Our
            Service, prior to the change becoming effective and update the "Last
            updated" date at the top of this Privacy Policy.
          </p>
          <p className="subHeading">
            You are advised to review this Privacy Policy periodically for any
            changes. Changes to this Privacy Policy are effective when they are
            posted on this page.
          </p>
        </div>
      </div>
      <Footer />
    </>
  );
};

export default PrivacyPolicy;
